Repository discopop-project/discopop, pull requests merged in 2023-01, with the labels that each got.

#276 chore(explorer): sort classified variables
  discopop_explorer/utils.py
  discopop_explorer/variable.py
Labels: enhancement, cleanup, quick

#278 Dump pet to gephi
  discopop_explorer/PETGraphX.py
Labels: quick

#279 GUI: Scrollable Suggestions
  discopop_wizard/classes/Suggestion.py
  discopop_wizard/screens/suggestions/overview.py
Labels: quick, GUI

#280 GUI: Scrollable Configuration
  discopop_wizard/screens/main.py
Labels: quick, GUI

#277 mark unused functions
  discopop_explorer/PETGraphX.py
Labels: quick

#281 stability improvements by loading default values for non existing settings
  discopop_wizard/classes/Settings.py
Labels: quick, GUI

#285 minor improvement to detection of variable definition lines
  DiscoPoP/DiscoPoP.cpp
Labels: enhancement, quick
