Repository discopop-project/discopop, pull requests merged in 2024-01, with the labels that each got.

#515 feat(explorer)[PE Graph creation]: calculate loop indices as metadata
  discopop_explorer/PEGraphX.py
  discopop_explorer/pattern_detection.py
Labels: enhancement

#518 doc(cmake): print DiscoPoP Version to be installed
  CMakeLists.txt
Labels: documentation

#526 fix(code_generator): potential type error
  discopop_library/CodeGenerator/classes/UnpackedSuggestion.py
Labels: bug

#527 feat: create symlinks on cmake build
  scripts/CMakeLists.txt
Labels: enhancement

#529 feat(optimizer): graph pruning
  .github/workflows/tests/profiler.sh
  DiscoPoP/DiscoPoP.cpp
  DiscoPoP/DiscoPoP.hpp
  discopop_explorer/pattern_detectors/PatternBase.py
  discopop_library/PatchGenerator/from_json_patterns.py
  discopop_library/discopop_optimizer/CostModels/utilities.py
  discopop_library/discopop_optimizer/OptimizerArguments.py
  discopop_library/discopop_optimizer/PETParser/PETParser.py
  discopop_library/discopop_optimizer/__main__.py
  discopop_library/discopop_optimizer/optimization/greedy.py
  discopop_library/discopop_optimizer/suggestions/optimizers/loop_collapse.py
  discopop_library/discopop_optimizer/utilities/MOGUtilities.py
  discopop_library/discopop_optimizer/utilities/optimization/LocalOptimization/TopDown.py
  rtlib/CMakeLists.txt
  rtlib/cu_taken_branch_counter.cpp
  rtlib/cu_taken_branch_counter.hpp
Labels: enhancement

#538 feat(optimizer): ignore loop indices for update calculation
  discopop_library/discopop_optimizer/DataTransfers/DataTransfers.py
  discopop_library/discopop_optimizer/UpdateOptimization/RemoveLoopIndexUpdates.py
  discopop_library/discopop_optimizer/classes/context/ContextObject.py
  discopop_library/discopop_optimizer/classes/context/Update.py
Labels: enhancement

#535 Format files
  DiscoPoP/DiscoPoP.cpp
  README.md
  docs/.gitignore
  docs/data/Parallel_patterns/pipeline.md
  docs/data/Program_execution_graph.md
  docs/data/data.md
  docs/examples/examples.md
  docs/examples/walk_through.md
  docs/index.md
  docs/setup/discopop.md
  docs/setup/setup.md
  docs/tools/Config_provider.md
  docs/tools/Explorer.md
  docs/tools/Optimizer.md
  docs/tools/Patch_applicator.md
  docs/tools/Patch_generator.md
  docs/tools/Scripts_and_wrappers.md
  docs/tools/organization_chart.graphml
  docs/tools/tools.md
  rtlib/cu_taken_branch_counter.cpp
  rtlib/cu_taken_branch_counter.hpp
  scripts/CMakeLists.txt
  share/lib/DPUtils.cpp
  test/optimizer/loop_collapse/negative/simple_1/src/code.cpp
  test/optimizer/loop_collapse/negative/simple_1/test.py
  test/optimizer/loop_collapse/positive/simple_1/src/code.cpp
  test/optimizer/loop_collapse/positive/simple_1/test.py
Labels: cleanup

#539 update documentation: vscx no longer requires settings for discopop/hotspot detection paths
  docs/setup/vscx.md
Labels: documentation, quick
